# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UM2hnAgbRi2PLBmlXxKgQGaq5kTcnmhk
"""

import random 

sample_data = 1000000
list_of_cards =range(0,52)
#this list represents cards with cards from 0-12 being spades,
# 13-25 being clubs,26-38 being hearts and 39 -51 being diamonds 
#where each suit ordered in ace,2,3,4,5,6,7,8,9,10,Joker,Queen,King
#i.e first element is an ace ,our program randomly selects 2 cards from this suit
#without replacement and checks average value of aces obtained 
count=0
for i in range(sample_data):
   a,b=random.sample(list_of_cards,2)
   if(a%13==0):
     count+=1
   if(b%13==0):
     count+=1  
   
prob_ace = count / sample_data

print("simulation results")
print("average value of number of aces obtained is (E(X)): ",prob_ace)
print("   ")
print("theoretical result")
print("average value of number of aces is (E(X)): 0.153846153 or 2/13")

print("Both sets of results are approximately the same")