# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UM2hnAgbRi2PLBmlXxKgQGaq5kTcnmhk
"""

import random 

sample_data = 1000000
list_of_cards =[0]*48
list_of_cards+=[1]*4
number_of_aces=[0,0,0]
#list_of_cards has 48 non-aces and 4 aces,
#where 0 denotes non ace and 1 denotes ace 
count=0
for i in range(sample_data):
   a,b=random.sample(list_of_cards,2)
   if(a==0 and b==0):
      number_of_aces[0]+=1
   elif(a==1 and b==1):
      count+=2
      number_of_aces[2]+=1
   else:
      count+=1
      number_of_aces[1]+=1     
   
prob_ace = count / sample_data

print("simulation results")
print("average value of number of aces obtained is (E(X)): ",prob_ace)
print("we ran the simulation ",sample_data," times ,out of which we got")
print("no ace's  : ",number_of_aces[0]," times")
print("only 1 ace: ",number_of_aces[1]," times")
print("both ace's: ",number_of_aces[2]," times")
print("   ")
print("theoretical result")
print("average value of number of aces is (E(X)): 0.153846153 or 2/13")

print("Both sets of results are approximately the same")
