# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ebfmdqCHfLVuoydr2UCjIzjy2QHZL1V
"""

import numpy as np
import random
from scipy.stats import bernoulli 
import matplotlib.pyplot as plt
sample=100000
true=0
all=0
#a=0 means H is transmitted,b=0 means H is received
#a=1 means L is transmitted,b=1 means L is received
#true= number of times a=0 and b=0,all =number of times when b=0
a=np.empty((1,sample),dtype=int)
b=np.empty((1,sample),dtype=int)
a=bernoulli.rvs(size=(1,sample),p=0.90)
for i in range(0,sample):
  if(a[0,i]==0):
    b[0,i]=bernoulli.rvs(p=0.7)
  else:
    b[0,i]=bernoulli.rvs(p=0.2)  
for i in range(sample):
  if a[0,i]==0 and b[0,i]==0 :
    true+=1
    all+=1 
  elif a[0,i]==1 and b[0,i]==0:
    all+=1      

answer=true/all
print("Number of times when h was received is",all)
print("Number of times when h was transmitted and h is received is",true)
print("Calculated probability of h being transmitted when h is received is",answer) 
print("Theoretical probability is 0.04 \nDifference between theoretical and calculated probability is",answer-0.04)
print("Theoretical and calculated values very close hence simulation accurate")