# -*- coding: utf-8 -*-
"""assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WsPk0IbFkdmAZGkNFpyRKweOQcmEhK6u
"""

import numpy as np
import random
from scipy.stats import bernoulli 
import matplotlib.pyplot as plt
sample=100000
#true denotes all cases when p=0 and q=0
#all denotes all cases when q=0
#p and q correspond to random variables P and Q in qn
#Pr(p=1) and Pr(q=1|p=1) given in qn
#Pr(q=1|p=0) found using Pr(q=1)=Pr(p=0)Pr(q=1|p=0)+Pr(p=1)Pr(q=1|p=1)
#where value of Pr(q=1) was found in solution
#Pr(p=1)=0.25,Pr(q=1)=1/6,Pr(q=1|p=1)=1/3,Pr(p=1|q=1)=1/2
true=0
all=0
p=np.empty(sample,dtype=int)
q=np.empty(sample,dtype=int)
p=bernoulli.rvs(size=sample,p=0.25)
for i in range(0,sample):
  if(p[i]==0):
    q[i]=bernoulli.rvs(p=(1/9))
  else:
    q[i]=bernoulli.rvs(p=(1/3))
for i in range(sample):
  if p[i]==0 and q[i]==0 :
    true+=1
    all+=1 
  elif p[i]==1 and q[i]==0:
    all+=1   
print("Calculated probability is ",true/all)     
print("Theoretical probability is 0.8")